# Generated by Django 3.2 on 2021-04-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
    ]
