# Generated by Django 3.2 on 2021-04-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0002_alter_profile_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('post', models.TextField(max_length=150)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoods.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='hoods.profile')),
            ],
        ),
    ]
