# Generated by Django 3.2 on 2021-04-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0003_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
