# Generated by Django 3.2 on 2021-04-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0004_rename_post_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-pk']},
        ),
    ]
